//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreatsManager.QuantitativeRisk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreatsManager.QuantitativeRisk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Schema that collects properties to evaluate the value of Assets..
        /// </summary>
        internal static string AssetSchemaDescription {
            get {
                return ResourceManager.GetString("AssetSchemaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Schema that collects the configuration information for the Quantitative Risk Engine, to be stored in the Threat Model..
        /// </summary>
        internal static string ConfigurationPropertySchemaDescription {
            get {
                return ResourceManager.GetString("ConfigurationPropertySchemaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency used within the Threat Model..
        /// </summary>
        internal static string CurrencyProperty {
            get {
                return ResourceManager.GetString("CurrencyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://threatsmanager.com/tm/2020.
        /// </summary>
        internal static string DefaultNamespace {
            get {
                return ResourceManager.GetString("DefaultNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Schema that collects the evaluation processing data for the Quantitative Risk Engine, to be associated to the Scenario..
        /// </summary>
        internal static string EvaluationPropertySchemaDescription {
            get {
                return ResourceManager.GetString("EvaluationPropertySchemaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantitativeRiskEval.
        /// </summary>
        internal static string EvaluationSchemaName {
            get {
                return ResourceManager.GetString("EvaluationSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context associated to the Facts.
        /// </summary>
        internal static string FactContextProperty {
            get {
                return ResourceManager.GetString("FactContextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property containing the values of the parameters required by the Fact Provider..
        /// </summary>
        internal static string FactProviderParamsProperty {
            get {
                return ResourceManager.GetString("FactProviderParamsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Fact Provider..
        /// </summary>
        internal static string FactProviderProperty {
            get {
                return ResourceManager.GetString("FactProviderProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of the Facts known within the Threat Model.
        /// </summary>
        internal static string FactsProperty {
            get {
                return ResourceManager.GetString("FactsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Event Frequency is not valid.
        /// </summary>
        internal static string InvalidLEF {
            get {
                return ResourceManager.GetString("InvalidLEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Loss Event Frequency does not define a valid distribution.
        /// </summary>
        internal static string InvalidLEFDistribution {
            get {
                return ResourceManager.GetString("InvalidLEFDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Primary Losses.
        /// </summary>
        internal static string InvalidPL {
            get {
                return ResourceManager.GetString("InvalidPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Loss for {0} is not valid.
        /// </summary>
        internal static string InvalidPrimaryLoss {
            get {
                return ResourceManager.GetString("InvalidPrimaryLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk is not valid.
        /// </summary>
        internal static string InvalidRisk {
            get {
                return ResourceManager.GetString("InvalidRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario is not valid.
        /// </summary>
        internal static string InvalidScenario {
            get {
                return ResourceManager.GetString("InvalidScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Loss for {0} is not valid.
        /// </summary>
        internal static string InvalidSecondaryLoss {
            get {
                return ResourceManager.GetString("InvalidSecondaryLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Secondary Losses.
        /// </summary>
        internal static string InvalidSL {
            get {
                return ResourceManager.GetString("InvalidSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Secondary Loss Event Frequency.
        /// </summary>
        internal static string InvalidSLEF {
            get {
                return ResourceManager.GetString("InvalidSLEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Loss Event Frequency does not define a valid distribution.
        /// </summary>
        internal static string InvalidSLEFDistribution {
            get {
                return ResourceManager.GetString("InvalidSLEFDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property containing the number of iterations to use for the Monte Carlo simulation..
        /// </summary>
        internal static string IterationsProperty {
            get {
                return ResourceManager.GetString("IterationsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property containing the Lower Percentile configuration..
        /// </summary>
        internal static string LowerPercentileProperty {
            get {
                return ResourceManager.GetString("LowerPercentileProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Primary Loss is defined.
        /// </summary>
        internal static string NoPrimaryLoss {
            get {
                return ResourceManager.GetString("NoPrimaryLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Secondary Loss is defined.
        /// </summary>
        internal static string NoSecondaryLoss {
            get {
                return ResourceManager.GetString("NoSecondaryLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk is not defined.
        /// </summary>
        internal static string NullRisk {
            get {
                return ResourceManager.GetString("NullRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Loss Event Frequency cannot be null.
        /// </summary>
        internal static string NullSLEF {
            get {
                return ResourceManager.GetString("NullSLEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantitative Risk.
        /// </summary>
        internal static string QuantitativeRiskSchemaName {
            get {
                return ResourceManager.GetString("QuantitativeRiskSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference measure configuration..
        /// </summary>
        internal static string ReferenceMeasureProperty {
            get {
                return ResourceManager.GetString("ReferenceMeasureProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        internal static string RiskProperty {
            get {
                return ResourceManager.GetString("RiskProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of the Thresholds to determine the Severities from the estimated most probable ALE..
        /// </summary>
        internal static string ThresholdsProperty {
            get {
                return ResourceManager.GetString("ThresholdsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Event Frequency cannot be undefined.
        /// </summary>
        internal static string UndefinedLEF {
            get {
                return ResourceManager.GetString("UndefinedLEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Magnitude cannot be undefined.
        /// </summary>
        internal static string UndefinedLM {
            get {
                return ResourceManager.GetString("UndefinedLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property containing the Upper Percentile configuration..
        /// </summary>
        internal static string UpperPercentileProperty {
            get {
                return ResourceManager.GetString("UpperPercentileProperty", resourceCulture);
            }
        }
    }
}
