// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ThreatsManager.Mitre.Capec
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.Collections.Generic;

/// <summary>
/// The StakeholderEnumeration simple type defines the different types of users within the CAPEC community.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://capec.mitre.org/capec-3")]
public enum StakeholderEnumeration
{
    [XmlEnumAttribute("Academic Researchers")]
    AcademicResearchers,
    [XmlEnumAttribute("Applied Researchers")]
    AppliedResearchers,
    [XmlEnumAttribute("Assessment Customers")]
    AssessmentCustomers,
    [XmlEnumAttribute("Assessment Vendors")]
    AssessmentVendors,
    [XmlEnumAttribute("CAPEC Team")]
    CAPECTeam,
    Educators,
    [XmlEnumAttribute("Information Providers")]
    InformationProviders,
    [XmlEnumAttribute("Software Customers")]
    SoftwareCustomers,
    [XmlEnumAttribute("Software Designers")]
    SoftwareDesigners,
    [XmlEnumAttribute("Software Developers")]
    SoftwareDevelopers,
    [XmlEnumAttribute("Software Vendors")]
    SoftwareVendors,
    Other,
}
}
#pragma warning restore
