// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// ActionContextTypeEnum is a (non-exhaustive) enumeration of cyber observable action contexts.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(Namespace="http://cybox.mitre.org/cybox-2")]
public enum ActionContextTypeEnum
{
    /// <summary>
    /// Specifies that the cyber observable action occurred on a host.
    /// </summary>
    Host,
    /// <summary>
    /// Specifies that the cyber observable action occurred on a network.
    /// </summary>
    Network,
}
}
#pragma warning restore
