// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The Type field is optional and utilizes a standardized controlled vocabulary to specify the basic type of the action that was performed.
/// </summary>
/// <summary>
/// This field is implemented through the xsi:type controlled vocabulary extension mechanism. The default vocabulary type is ActionTypeVocab in the http://cybox.mitre.org/default_vocabularies-2 namespace. This type is defined in the cybox_default_vocabularies.xsd file or at the URL http://cybox.mitre.org/XMLSchema/default_vocabularies/2.0.1/cybox_default_vocabularies.xsd.
/// </summary>
/// <summary>
/// Users may also define their own vocabulary using the type extension mechanism (by specifying a vocabulary name and/or reference using the vocab_name and vocab_reference attributes, respectively) or simply use this as a string field.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/cybox-2")]
public partial class ActionType
{
    #region Private fields
    private ControlledVocabularyStringType _type;
    private ControlledVocabularyStringType _name;
    private StructuredTextType _description;
    private List<string> _action_Aliases;
    private List<ActionArgumentType> _action_Arguments;
    private LocationType _location;
    private MeasureSourceType _discovery_Method;
    private List<AssociatedObjectType> _associated_Objects;
    private List<ActionRelationshipType> _relationships;
    private FrequencyType _frequency;
    private System.Xml.XmlQualifiedName _id;
    private System.Xml.XmlQualifiedName _idref;
    private string _ordinal_position;
    private ActionStatusTypeEnum _action_status;
    private ActionContextTypeEnum _context;
    private DateTime _timestamp;
    private string _timestamp_precision;
    #endregion
    
    /// <summary>
    /// ActionType class constructor
    /// </summary>
    public ActionType()
    {
        _frequency = new FrequencyType();
        _relationships = new List<ActionRelationshipType>();
        _associated_Objects = new List<AssociatedObjectType>();
        _discovery_Method = new MeasureSourceType();
        _location = new LocationType();
        _action_Arguments = new List<ActionArgumentType>();
        _action_Aliases = new List<string>();
        _description = new StructuredTextType();
        _name = new ControlledVocabularyStringType();
        _type = new ControlledVocabularyStringType();
        _timestamp_precision = "second";
    }
    
    public ControlledVocabularyStringType Type
    {
        get => _type;
        set => _type = value;
    }
    
    public ControlledVocabularyStringType Name
    {
        get => _name;
        set => _name = value;
    }
    
    public StructuredTextType Description
    {
        get => _description;
        set => _description = value;
    }
    
    [XmlArrayItem("Action_Alias", IsNullable=false)]
    public List<string> Action_Aliases
    {
        get => _action_Aliases;
        set => _action_Aliases = value;
    }
    
    [XmlArrayItem("Action_Argument", IsNullable=false)]
    public List<ActionArgumentType> Action_Arguments
    {
        get => _action_Arguments;
        set => _action_Arguments = value;
    }
    
    public LocationType Location
    {
        get => _location;
        set => _location = value;
    }
    
    public MeasureSourceType Discovery_Method
    {
        get => _discovery_Method;
        set => _discovery_Method = value;
    }
    
    [XmlArrayItem("Associated_Object", IsNullable=false)]
    public List<AssociatedObjectType> Associated_Objects
    {
        get => _associated_Objects;
        set => _associated_Objects = value;
    }
    
    [XmlArrayItem("Relationship", IsNullable=false)]
    public List<ActionRelationshipType> Relationships
    {
        get => _relationships;
        set => _relationships = value;
    }
    
    public FrequencyType Frequency
    {
        get => _frequency;
        set => _frequency = value;
    }
    
    [XmlAttribute]
    public System.Xml.XmlQualifiedName id
    {
        get => _id;
        set => _id = value;
    }
    
    [XmlAttribute]
    public System.Xml.XmlQualifiedName idref
    {
        get => _idref;
        set => _idref = value;
    }
    
    [XmlAttribute(DataType="positiveInteger")]
    public string ordinal_position
    {
        get => _ordinal_position;
        set => _ordinal_position = value;
    }
    
    [XmlAttribute]
    public ActionStatusTypeEnum action_status
    {
        get => _action_status;
        set => _action_status = value;
    }
    
    [XmlAttribute]
    public ActionContextTypeEnum context
    {
        get => _context;
        set => _context = value;
    }
    
    [XmlAttribute]
    public DateTime timestamp
    {
        get => _timestamp;
        set => _timestamp = value;
    }
    
    [XmlAttribute]
    [DefaultValue("second")]
    public string timestamp_precision
    {
        get => _timestamp_precision;
        set => _timestamp_precision = value;
    }
}
}
#pragma warning restore
