// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class Attack_Execution_FlowAttack_Phase
{
    #region Private fields
    private List<Attack_Execution_FlowAttack_PhaseAttack_Step> _attack_Steps;
    private string _id;
    private Attack_Execution_FlowAttack_PhaseName _name;
    #endregion
    
    /// <summary>
    /// Attack_Execution_FlowAttack_Phase class constructor
    /// </summary>
    public Attack_Execution_FlowAttack_Phase()
    {
        _attack_Steps = new List<Attack_Execution_FlowAttack_PhaseAttack_Step>();
    }
    
    [XmlArrayItem("Attack_Step", IsNullable=false)]
    public List<Attack_Execution_FlowAttack_PhaseAttack_Step> Attack_Steps
    {
        get => _attack_Steps;
        set => _attack_Steps = value;
    }
    
    [XmlAttribute(DataType="integer")]
    public string ID
    {
        get => _id;
        set => _id = value;
    }
    
    [XmlAttribute]
    public Attack_Execution_FlowAttack_PhaseName Name
    {
        get => _name;
        set => _name = value;
    }
}
}
#pragma warning restore
