// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public enum Attack_PatternTypeAttacker_Skill_or_Knowledge_RequiredSkill_or_Knowledge_Level
{
    Low,
    Medium,
    High,
}
}
#pragma warning restore
