// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class Attack_PatternTypeTechnical_Context
{
    #region Private fields
    private List<Attack_PatternTypeTechnical_ContextArchitectural_Paradigm> _architectural_Paradigms;
    private List<Attack_PatternTypeTechnical_ContextFramework> _frameworks;
    private List<Attack_PatternTypeTechnical_ContextPlatform> _platforms;
    private List<Attack_PatternTypeTechnical_ContextLanguage> _languages;
    #endregion
    
    /// <summary>
    /// Attack_PatternTypeTechnical_Context class constructor
    /// </summary>
    public Attack_PatternTypeTechnical_Context()
    {
        _languages = new List<Attack_PatternTypeTechnical_ContextLanguage>();
        _platforms = new List<Attack_PatternTypeTechnical_ContextPlatform>();
        _frameworks = new List<Attack_PatternTypeTechnical_ContextFramework>();
        _architectural_Paradigms = new List<Attack_PatternTypeTechnical_ContextArchitectural_Paradigm>();
    }
    
    [XmlArrayItem("Architectural_Paradigm", IsNullable=false)]
    public List<Attack_PatternTypeTechnical_ContextArchitectural_Paradigm> Architectural_Paradigms
    {
        get => _architectural_Paradigms;
        set => _architectural_Paradigms = value;
    }
    
    [XmlArrayItem("Framework", IsNullable=false)]
    public List<Attack_PatternTypeTechnical_ContextFramework> Frameworks
    {
        get => _frameworks;
        set => _frameworks = value;
    }
    
    [XmlArrayItem("Platform", IsNullable=false)]
    public List<Attack_PatternTypeTechnical_ContextPlatform> Platforms
    {
        get => _platforms;
        set => _platforms = value;
    }
    
    [XmlArrayItem("Language", IsNullable=false)]
    public List<Attack_PatternTypeTechnical_ContextLanguage> Languages
    {
        get => _languages;
        set => _languages = value;
    }
}
}
#pragma warning restore
