// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class Attack_PatternTypeCIA_Impact
{
    #region Private fields
    private Attack_PatternTypeCIA_ImpactConfidentiality_Impact _confidentiality_Impact;
    private Attack_PatternTypeCIA_ImpactIntegrity_Impact _integrity_Impact;
    private Attack_PatternTypeCIA_ImpactAvailability_Impact _availability_Impact;
    #endregion
    
    public Attack_PatternTypeCIA_ImpactConfidentiality_Impact Confidentiality_Impact
    {
        get => _confidentiality_Impact;
        set => _confidentiality_Impact = value;
    }
    
    public Attack_PatternTypeCIA_ImpactIntegrity_Impact Integrity_Impact
    {
        get => _integrity_Impact;
        set => _integrity_Impact = value;
    }
    
    public Attack_PatternTypeCIA_ImpactAvailability_Impact Availability_Impact
    {
        get => _availability_Impact;
        set => _availability_Impact = value;
    }
}
}
#pragma warning restore
