// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public enum BlockBlock_Nature
{
    Good_Code,
    Bad_Code,
    Mitigation_Code,
    Attack,
    Result,
    List,
    Numeric_List,
}
}
#pragma warning restore
