// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class CategoryAttacker_Skill_or_Knowledge_Required
{
    #region Private fields
    private CategoryAttacker_Skill_or_Knowledge_RequiredSkill_or_Knowledge_Level _skill_or_Knowledge_Level;
    private Structured_Text_Type _skill_or_Knowledge_Type;
    #endregion
    
    /// <summary>
    /// CategoryAttacker_Skill_or_Knowledge_Required class constructor
    /// </summary>
    public CategoryAttacker_Skill_or_Knowledge_Required()
    {
        _skill_or_Knowledge_Type = new Structured_Text_Type();
    }
    
    public CategoryAttacker_Skill_or_Knowledge_RequiredSkill_or_Knowledge_Level Skill_or_Knowledge_Level
    {
        get => _skill_or_Knowledge_Level;
        set => _skill_or_Knowledge_Level = value;
    }
    
    public Structured_Text_Type Skill_or_Knowledge_Type
    {
        get => _skill_or_Knowledge_Type;
        set => _skill_or_Knowledge_Type = value;
    }
}
}
#pragma warning restore
