// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class CategoryRelated_Weakness
{
    #region Private fields
    private string _cWE_ID;
    private CategoryRelated_WeaknessWeakness_Relationship_Type _weakness_Relationship_Type;
    #endregion
    
    [XmlElement(DataType="integer")]
    public string CWE_ID
    {
        get => _cWE_ID;
        set => _cWE_ID = value;
    }
    
    public CategoryRelated_WeaknessWeakness_Relationship_Type Weakness_Relationship_Type
    {
        get => _weakness_Relationship_Type;
        set => _weakness_Relationship_Type = value;
    }
}
}
#pragma warning restore
