// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public enum Common_ConsequenceTypeConsequence_Technical_Impact
{
    [XmlEnum("Modify memory")]
    Modifymemory,
    [XmlEnum("Read memory")]
    Readmemory,
    [XmlEnum("Modify files or directories")]
    Modifyfilesordirectories,
    [XmlEnum("Read files or directories")]
    Readfilesordirectories,
    [XmlEnum("Modify application data")]
    Modifyapplicationdata,
    [XmlEnum("Read application data")]
    Readapplicationdata,
    [XmlEnum("DoS: crash / exit / restart")]
    DoScrashexitrestart,
    [XmlEnum("DoS: amplification")]
    DoSamplification,
    [XmlEnum("DoS: instability")]
    DoSinstability,
    [XmlEnum("DoS: resource consumption (CPU)")]
    DoSresourceconsumptionCPU,
    [XmlEnum("DoS: resource consumption (memory)")]
    DoSresourceconsumptionmemory,
    [XmlEnum("DoS: resource consumption (other)")]
    DoSresourceconsumptionother,
    [XmlEnum("Execute unauthorized code or commands")]
    Executeunauthorizedcodeorcommands,
    [XmlEnum("Gain privileges / assume identity")]
    Gainprivilegesassumeidentity,
    [XmlEnum("Bypass protection mechanism")]
    Bypassprotectionmechanism,
    [XmlEnum("Hide activities")]
    Hideactivities,
    [XmlEnum("Alter execution logic")]
    Alterexecutionlogic,
    Other,
    [XmlEnum("\"Varies by context\"")]
    Variesbycontext,
    [XmlEnum("Quality degradation")]
    Qualitydegradation,
    [XmlEnum("Unexpected State")]
    UnexpectedState,
}
}
#pragma warning restore
