// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The CompilerInformalDescriptionType contains the informal description of this compiler instance.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class CompilerInformalDescriptionType
{
    #region Private fields
    private string _compiler_Name;
    private string _compiler_Version;
    #endregion
    
    /// <summary>
    /// This field contains the name of the compiler.
    /// </summary>
    public string Compiler_Name
    {
        get => _compiler_Name;
        set => _compiler_Name = value;
    }
    
    /// <summary>
    /// This field contains the version of the compiler.
    /// </summary>
    public string Compiler_Version
    {
        get => _compiler_Version;
        set => _compiler_Version = value;
    }
}
}
#pragma warning restore
