// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// ConditionTypeEnum is a (non-exhaustive) enumeration of condition types.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public enum ConditionTypeEnum
{
    /// <summary>
    /// Specifies the equality or = condition.
    /// </summary>
    Equals,
    /// <summary>
    /// Specifies the "does not equal" or != condition.
    /// </summary>
    DoesNotEqual,
    /// <summary>
    /// Specifies the "contains" condition.
    /// </summary>
    Contains,
    /// <summary>
    /// Specifies the "does not contain" condition.
    /// </summary>
    DoesNotContain,
    /// <summary>
    /// Specifies the "starts with" condition.
    /// </summary>
    StartsWith,
    /// <summary>
    /// Specifies the "ends with" condition.
    /// </summary>
    EndsWith,
    /// <summary>
    /// Specifies the "greater than" condition.
    /// </summary>
    GreaterThan,
    /// <summary>
    /// Specifies the "greater than or equal to" condition.
    /// </summary>
    GreaterThanOrEqual,
    /// <summary>
    /// Specifies the "less than" condition.
    /// </summary>
    LessThan,
    /// <summary>
    /// Specifies the "less than or equal" condition.
    /// </summary>
    LessThanOrEqual,
    /// <summary>
    /// The pattern is met if the given value lies between the values indicated in the field value body, inclusive of the bounding values themselves. The field value body MUST contain at least 2 values to be valid. If the field value body contains more than 2 values, then only the greatest and least values are considered. (I.e., If the body contains "2,4,6", then an InclusiveBetween condition would be satisfied if the observed value fell between 2 and 6, inclusive. Since this is an inclusive range, an observed value of 2 or 6 would fit the pattern in this example.) As such, always treat the InclusiveBetween condition as applying to a single range for the purpose of evaluating the apply_condition attribute.
    /// </summary>
    InclusiveBetween,
    /// <summary>
    /// The pattern is met if the given value lies between the values indicated in the field value body, exclusive of the bounding values themselves. The field value body MUST contain at least 2 values to be valid. If the field value body contains more than 2 values, then only the greatest and least values are considered. (I.e., If the body contains "2,4,6", then an InclusiveBetween condition would be satisfied if the observed value fell between 2 and 6, exclusive. Since this is an exclusive range, an observed value of 2 or 6 would not fit the pattern in this example.) As such, always treat the ExclusiveBetween condition as applying to a single range for the purpose of evaluating the apply_condition attribute.
    /// </summary>
    ExclusiveBetween,
    /// <summary>
    /// Specifies the condition that a value fits a given pattern.
    /// </summary>
    FitsPattern,
    /// <summary>
    /// Specifies the condition of bitwise AND. Specifically, when applying this pattern, a given value is bitwise-ANDed with the bit_mask attribute value (which must be present). If the result is identical to the value provided in the body of this field value, the pattern is considered fulfilled.
    /// </summary>
    BitwiseAnd,
    /// <summary>
    /// Specifies the condition of bitwise OR. Specifically, when applying this pattern, a given value is bitwise-ORed with the bit_mask attribute value (which must be present). If the result is identical to the value provided in the body of this field value, the pattern is considered fulfilled.
    /// </summary>
    BitwiseOr,
    /// <summary>
    /// Specifies the condition of bitwise XOR. Specifically, when applying this pattern, a given value is bitwise-XORed with the bit_mask attribute value (which must be present). If the result is identical to the value provided in the body of this field value, the pattern is considered fulfilled.
    /// </summary>
    BitwiseXor,
}
}
#pragma warning restore
