// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class Custom_Attack_StepTypeSecurity_ControlObservable_Evidence
{
    #region Private fields
    private ObservablesType2 _item;
    private ItemChoiceType _itemElementName;
    #endregion
    
    [XmlElement("IfNotPresent_Observables", typeof(ObservablesType2))]
    [XmlElement("IfPresent_Observables", typeof(ObservablesType2))]
    [XmlChoiceIdentifier("ItemElementName")]
    public ObservablesType2 Item
    {
        get => _item;
        set => _item = value;
    }
    
    [XmlIgnore]
    public ItemChoiceType ItemElementName
    {
        get => _itemElementName;
        set => _itemElementName = value;
    }
}
}
#pragma warning restore
