// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The DataSizeUnitsEnum is a (non-exhaustive) enumeration of data size units.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public enum DataSizeUnitsEnum
{
    /// <summary>
    /// Specifies an object size in Bytes.
    /// </summary>
    Bytes,
    /// <summary>
    /// Specifies an object size in Kilobytes.
    /// </summary>
    Kilobytes,
    /// <summary>
    /// Specifies an object size in Megabytes.
    /// </summary>
    Megabytes,
}
}
#pragma warning restore
