// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The DataSentEffectType type is intended to characterize the effects of actions upon objects where some data is sent, such as a byte sequence on a socket.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/cybox-2")]
public partial class DataSentEffectType : DefinedEffectType
{
    #region Private fields
    private DataSegmentType _data;
    #endregion
    
    /// <summary>
    /// DataSentEffectType class constructor
    /// </summary>
    public DataSentEffectType()
    {
        _data = new DataSegmentType();
    }
    
    /// <summary>
    /// The Data field specifies the data that was sent on the object, or from the object, by the action.
    /// </summary>
    public DataSegmentType Data
    {
        get => _data;
        set => _data = value;
    }
}
}
#pragma warning restore
