// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// This type is used as a replacement for the standard xs:dateTime type but allows for the representation of the precision of the dateTime.  If the precision is given, consumers must ignore the portions of this field that is more precise than the given precision. Producers should zero-out (fill with zeros) digits in the dateTime that are required by the xs:dateTime datatype but are beyond the specified precision.
/// </summary>
/// <summary>
/// In order to avoid ambiguity, it is strongly suggested that all dateTimes include a specification of the timezone if it is known.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class DateTimeWithPrecisionType
{
    #region Private fields
    private string _precision;
    private DateTime _value;
    #endregion
    
    /// <summary>
    /// DateTimeWithPrecisionType class constructor
    /// </summary>
    public DateTimeWithPrecisionType()
    {
        _precision = "second";
    }
    
    /// <summary>
    /// The precision of the associated dateTime. If omitted, the default is "second", meaning the full field value (including fractional seconds).
    /// </summary>
    [XmlAttribute]
    [DefaultValue("second")]
    public string precision
    {
        get => _precision;
        set => _precision = value;
    }
    
    [XmlText]
    public DateTime Value
    {
        get => _value;
        set => _value = value;
    }
}
}
#pragma warning restore
