// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// Possible values for representing date precision.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public enum DatePrecisionEnum
{
    /// <summary>
    /// Date is precise to the given year.
    /// </summary>
    year,
    /// <summary>
    /// Date is precise to the given month.
    /// </summary>
    month,
    /// <summary>
    /// Date is precise to the given day.
    /// </summary>
    day,
}
}
#pragma warning restore
