// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// This type is used as a replacement for the standard xs:date type but allows for the representation of the precision of the date. If the precision is given, consumers must ignore the portions of this field that is more precise than the given precision. Producers should zero-out (fill with zeros) digits in the date that are required by the xs:date datatype but are beyond the specified precision.
/// </summary>
/// <summary>
/// In order to avoid ambiguity, it is strongly suggested that all dates include a specification of the timezone if it is known.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class DateWithPrecisionType
{
    #region Private fields
    private DatePrecisionEnum _precision;
    private DateTime _value;
    #endregion
    
    /// <summary>
    /// DateWithPrecisionType class constructor
    /// </summary>
    public DateWithPrecisionType()
    {
        _precision = DatePrecisionEnum.day;
    }
    
    /// <summary>
    /// The precision of the associated date. If omitted, the default is "day", meaning the full field value.
    /// </summary>
    [XmlAttribute]
    [DefaultValue(DatePrecisionEnum.day)]
    public DatePrecisionEnum precision
    {
        get => _precision;
        set => _precision = value;
    }
    
    [XmlText(DataType="date")]
    public DateTime Value
    {
        get => _value;
        set => _value = value;
    }
}
}
#pragma warning restore
