// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The DependencyType contains information describing a single dependency for this tool.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class DependencyType
{
    #region Private fields
    private string _dependency_Type;
    private StructuredTextType _dependency_Description;
    #endregion
    
    /// <summary>
    /// DependencyType class constructor
    /// </summary>
    public DependencyType()
    {
        _dependency_Description = new StructuredTextType();
    }
    
    /// <summary>
    /// This field describes the type of this dependency instance.
    /// </summary>
    public string Dependency_Type
    {
        get => _dependency_Type;
        set => _dependency_Type = value;
    }
    
    /// <summary>
    /// This field contains a description of this dependency instance.
    /// </summary>
    public StructuredTextType Dependency_Description
    {
        get => _dependency_Description;
        set => _dependency_Description = value;
    }
}
}
#pragma warning restore
