// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The EventType is a complex type representing a cyber observable event that is dynamic in nature with specific action(s) taken against specific cyber relevant objects (e.g. a file is deleted, a registry key is created or an HTTP Get Request is received).
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/cybox-2")]
public partial class EventType
{
    #region Private fields
    private List<object> _items;
    private System.Xml.XmlQualifiedName _id;
    private System.Xml.XmlQualifiedName _idref;
    #endregion
    
    /// <summary>
    /// EventType class constructor
    /// </summary>
    public EventType()
    {
        _items = new List<object>();
    }
    
    [XmlElement("Actions", typeof(ActionsType))]
    [XmlElement("Description", typeof(StructuredTextType))]
    [XmlElement("Event", typeof(EventType))]
    [XmlElement("Frequency", typeof(FrequencyType))]
    [XmlElement("Location", typeof(LocationType))]
    [XmlElement("Observation_Method", typeof(MeasureSourceType))]
    [XmlElement("Type", typeof(ControlledVocabularyStringType))]
    public List<object> Items
    {
        get => _items;
        set => _items = value;
    }
    
    /// <summary>
    /// The id field specifies a unique id for this Event.
    /// </summary>
    [XmlAttribute]
    public System.Xml.XmlQualifiedName id
    {
        get => _id;
        set => _id = value;
    }
    
    /// <summary>
    /// The idref field specifies a unique id reference to an Event defined elsewhere.
    /// </summary>
    /// <summary>
    /// When idref is specified, the id attribute must not be specified, and any instance of this Event should not hold content unless an extension of the Event allows it.
    /// </summary>
    [XmlAttribute]
    public System.Xml.XmlQualifiedName idref
    {
        get => _idref;
        set => _idref = value;
    }
}
}
#pragma warning restore
