// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The ExecutionEnvironmentType contains information describing the execution environment of the tool.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class ExecutionEnvironmentType
{
    #region Private fields
    private ObjectPropertiesType _system;
    private ObjectPropertiesType _user_Account_Info;
    private string _command_Line;
    private DateTimeWithPrecisionType _start_Time;
    #endregion
    
    /// <summary>
    /// ExecutionEnvironmentType class constructor
    /// </summary>
    public ExecutionEnvironmentType()
    {
        _start_Time = new DateTimeWithPrecisionType();
    }
    
    /// <summary>
    /// This field contains information describing the system on which the tool was executed. System should be of type SystemObj:SystemObjectType.
    /// </summary>
    public ObjectPropertiesType System
    {
        get => _system;
        set => _system = value;
    }
    
    /// <summary>
    /// This field contains information describing the user account that executed the tool. User_Account_Info should be of type UserAccountObj:UserAccountObjectType.
    /// </summary>
    public ObjectPropertiesType User_Account_Info
    {
        get => _user_Account_Info;
        set => _user_Account_Info = value;
    }
    
    /// <summary>
    /// This field specifies the command line string used to run the tool.
    /// </summary>
    public string Command_Line
    {
        get => _command_Line;
        set => _command_Line = value;
    }
    
    /// <summary>
    /// This field specifies when the tool was run. In order to avoid ambiguity, it is strongly suggest that all timestamps in this field include a specification of the timezone if it is known.
    /// </summary>
    public DateTimeWithPrecisionType Start_Time
    {
        get => _start_Time;
        set => _start_Time = value;
    }
}
}
#pragma warning restore
