// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The LibraryType identifies a single library incorporated into the build of the tool.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class LibraryType
{
    #region Private fields
    private string _name;
    private string _version;
    #endregion
    
    /// <summary>
    /// This field identifies the name of the library.
    /// </summary>
    [XmlAttribute]
    public string name
    {
        get => _name;
        set => _name = value;
    }
    
    /// <summary>
    /// This field identifies the version of the library.
    /// </summary>
    [XmlAttribute]
    public string version
    {
        get => _version;
        set => _version = value;
    }
}
}
#pragma warning restore
