// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The LocationType is used to express geographic location information.
/// </summary>
/// <summary>
/// This type is extended through the xsi:type mechanism. The default type is CIQAddress3.0InstanceType in the http://cybox.mitre.org/extensions/Address#CIQAddress3.0-1 namespace. This type is defined in the extensions/location/ciq_address_3.0.xsd file or at the URL http://cybox.mitre.org/XMLSchema/extensions/location/ciq_address_3.0/1.0/ciq_address_3.0.xsd.
/// </summary>
/// <summary>
/// Those who wish to express a simple name may also do so by not specifying an xsi:type and using the Name field of this type.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class LocationType
{
    #region Private fields
    private string _name;
    private System.Xml.XmlQualifiedName _id;
    private System.Xml.XmlQualifiedName _idref;
    #endregion
    
    /// <summary>
    /// The Name field allows for expression of an location through a simple name.
    /// </summary>
    public string Name
    {
        get => _name;
        set => _name = value;
    }
    
    /// <summary>
    /// Specifies a unique ID for this Location.
    /// </summary>
    [XmlAttribute]
    public System.Xml.XmlQualifiedName id
    {
        get => _id;
        set => _id = value;
    }
    
    /// <summary>
    /// Specifies a reference to a unique ID defined elsewhere.
    /// </summary>
    [XmlAttribute]
    public System.Xml.XmlQualifiedName idref
    {
        get => _idref;
        set => _idref = value;
    }
}
}
#pragma warning restore
