// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class MetadataType
{
    #region Private fields
    private string _value;
    private List<MetadataType> _subDatum;
    private string _type;
    #endregion
    
    /// <summary>
    /// MetadataType class constructor
    /// </summary>
    public MetadataType()
    {
        _subDatum = new List<MetadataType>();
    }
    
    public string Value
    {
        get => _value;
        set => _value = value;
    }
    
    [XmlElement("SubDatum")]
    public List<MetadataType> SubDatum
    {
        get => _subDatum;
        set => _subDatum = value;
    }
    
    [XmlAttribute]
    public string type
    {
        get => _type;
        set => _type = value;
    }
}
}
#pragma warning restore
