// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// OperatorTypeEnum is a (non-exhaustive) enumeration of operators.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(Namespace="http://cybox.mitre.org/cybox-2")]
public enum OperatorTypeEnum
{
    /// <summary>
    /// Specifies the AND logical composition operation.
    /// </summary>
    AND,
    /// <summary>
    /// Specifies the OR logical composition operation.
    /// </summary>
    OR,
}
}
#pragma warning restore
