// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// Used to specify a name for a platform using a particular naming system and also allowing a reference pointing to more information about that naming scheme. For example, one could provide a CPE (Common Platform Enumeration) name using the CPE naming format. In this case, the system value could be "CPE" while the system_ref value could be "http://scap.nist.gov/specifications/cpe/".
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class PlatformIdentifierType : StringObjectPropertyType
{
    #region Private fields
    private string _system;
    private string _systemref;
    #endregion
    
    /// <summary>
    /// Indicates the naming system from which the indicated name was drawn.
    /// </summary>
    [XmlAttribute]
    public string system
    {
        get => _system;
        set => _system = value;
    }
    
    [XmlAttribute("system-ref", DataType="anyURI")]
    public string systemref
    {
        get => _systemref;
        set => _systemref = value;
    }
}
}
#pragma warning restore
