// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The Type field is optional and utilizes a standardized controlled vocabulary to specify the basic type of the action that was performed.
/// </summary>
/// <summary>
/// This field is implemented through the xsi:type controlled vocabulary extension mechanism. The default vocabulary type is ActionTypeVocab in the http://cybox.mitre.org/default_vocabularies-2 namespace. This type is defined in the cybox_default_vocabularies.xsd file or at the URL http://cybox.mitre.org/XMLSchema/default_vocabularies/2.0.1/cybox_default_vocabularies.xsd.
/// </summary>
/// <summary>
/// Users may also define their own vocabulary using the type extension mechanism (by specifying a vocabulary name and/or reference using the vocab_name and vocab_reference attributes, respectively) or simply use this as a string field.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/cybox-2")]
public partial class PoolsType
{
    #region Private fields
    private List<EventType> _event_Pool;
    private List<ActionType> _action_Pool;
    private List<ObjectType> _object_Pool;
    private List<PropertyType> _property_Pool;
    #endregion
    
    /// <summary>
    /// PoolsType class constructor
    /// </summary>
    public PoolsType()
    {
        _property_Pool = new List<PropertyType>();
        _object_Pool = new List<ObjectType>();
        _action_Pool = new List<ActionType>();
        _event_Pool = new List<EventType>();
    }
    
    [XmlArrayItem("Event", IsNullable=false)]
    public List<EventType> Event_Pool
    {
        get => _event_Pool;
        set => _event_Pool = value;
    }
    
    [XmlArrayItem("Action", IsNullable=false)]
    public List<ActionType> Action_Pool
    {
        get => _action_Pool;
        set => _action_Pool = value;
    }
    
    [XmlArrayItem("Object", IsNullable=false)]
    public List<ObjectType> Object_Pool
    {
        get => _object_Pool;
        set => _object_Pool = value;
    }
    
    [XmlArrayItem("Property", IsNullable=false)]
    public List<PropertyType> Property_Pool
    {
        get => _property_Pool;
        set => _property_Pool = value;
    }
}
}
#pragma warning restore
