// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The PropertyReadEffectType type is intended to characterize the effects of actions upon objects where some specific property is read from an object, such as the current running state of a process.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/cybox-2")]
public partial class PropertyReadEffectType : DefinedEffectType
{
    #region Private fields
    private string _name;
    private string _value;
    #endregion
    
    /// <summary>
    /// The Name field specifies the Name of the property being read.
    /// </summary>
    public string Name
    {
        get => _name;
        set => _name = value;
    }
    
    /// <summary>
    /// The Value field specifies the value of the property being read.
    /// </summary>
    public string Value
    {
        get => _value;
        set => _value = value;
    }
}
}
#pragma warning restore
