// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The PropertiesEnumeratedEffectType type is intended to characterize the effects of actions upon objects where some properties of the object are enumerated, such as the startup parameters for a process.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/cybox-2")]
public partial class PropertiesEnumeratedEffectType : DefinedEffectType
{
    #region Private fields
    private List<string> _properties;
    #endregion
    
    /// <summary>
    /// PropertiesEnumeratedEffectType class constructor
    /// </summary>
    public PropertiesEnumeratedEffectType()
    {
        _properties = new List<string>();
    }
    
    /// <summary>
    /// The Properties field specifies the properties that were enumerated as a result of the action on the object.
    /// </summary>
    [XmlArrayItem("Property", IsNullable=false)]
    public List<string> Properties
    {
        get => _properties;
        set => _properties = value;
    }
}
}
#pragma warning restore
