// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// Specifies the unique ID of the individual view element to which this relationship pertains. This ID must correspond to a View.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class RelationshipTypeRelationship_View_ID
{
    #region Private fields
    private RelationshipTypeRelationship_View_IDOrdinal _ordinal;
    private string _value;
    #endregion
    
    /// <summary>
    /// The ordinal attribute is used to determine if this relationship is the primary ChildOf relationship for this entry for a given Relationship_View_ID element.. This attribute can only have the value "Primary" and should only be included for the primary parent/child relationship.
    /// </summary>
    [XmlAttribute]
    public RelationshipTypeRelationship_View_IDOrdinal Ordinal
    {
        get => _ordinal;
        set => _ordinal = value;
    }
    
    [XmlText(DataType="integer")]
    public string Value
    {
        get => _value;
        set => _value = value;
    }
}
}
#pragma warning restore
