// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://capec.mitre.org/capec-2")]
public partial class RelationshipType
{
    #region Private fields
    private List<RelationshipTypeRelationship_View_ID> _relationship_Views;
    private List<string> _relationship_Chains;
    private RelationshipTypeRelationship_Target_Form _relationship_Target_Form;
    private List<RelationshipTypeRelationship_Nature> _relationship_Nature;
    private string _relationship_Target_ID;
    private Structured_Text_Type _relationship_Description;
    #endregion
    
    /// <summary>
    /// RelationshipType class constructor
    /// </summary>
    public RelationshipType()
    {
        _relationship_Description = new Structured_Text_Type();
        _relationship_Nature = new List<RelationshipTypeRelationship_Nature>();
        _relationship_Chains = new List<string>();
        _relationship_Views = new List<RelationshipTypeRelationship_View_ID>();
    }
    
    /// <summary>
    /// This element contains a list of the individual Views to which this relationship pertains.
    /// </summary>
    [XmlArrayItem("Relationship_View_ID", IsNullable=false)]
    public List<RelationshipTypeRelationship_View_ID> Relationship_Views
    {
        get => _relationship_Views;
        set => _relationship_Views = value;
    }
    
    /// <summary>
    /// This element contains a list of the individual Chains this relationship pertains to.
    /// </summary>
    [XmlArrayItem("Relationship_Chain_ID", DataType="integer", IsNullable=false)]
    public List<string> Relationship_Chains
    {
        get => _relationship_Chains;
        set => _relationship_Chains = value;
    }
    
    /// <summary>
    /// The Relationship_Target_Form element defines the form of the target of this relationship, such as Category, Attack Pattern, View or Compound_Element.
    /// </summary>
    public RelationshipTypeRelationship_Target_Form Relationship_Target_Form
    {
        get => _relationship_Target_Form;
        set => _relationship_Target_Form = value;
    }
    
    /// <summary>
    /// The Relationship_Nature element defines the nature of the relationship between this element and the target element, such as ChildOf, HasMember or Requires to name a few.
    /// </summary>
    [XmlElement("Relationship_Nature")]
    public List<RelationshipTypeRelationship_Nature> Relationship_Nature
    {
        get => _relationship_Nature;
        set => _relationship_Nature = value;
    }
    
    /// <summary>
    /// The Relationship_Target_ID specifies the unique ID of the target element of the relationship.
    /// </summary>
    [XmlElement(DataType="integer")]
    public string Relationship_Target_ID
    {
        get => _relationship_Target_ID;
        set => _relationship_Target_ID = value;
    }
    
    public Structured_Text_Type Relationship_Description
    {
        get => _relationship_Description;
        set => _relationship_Description = value;
    }
}
}
#pragma warning restore
