// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The StructuredTextType is a type representing a generalized structure for capturing structured or unstructured textual information such as descriptions of things.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class StructuredTextType
{
    #region Private fields
    private string _structuring_format;
    private string _value;
    #endregion
    
    /// <summary>
    /// Used to indicate a particular structuring format (e.g., HTML5) used within an instance of StructuredTextType. Note that if the markup tags used by this format would be interpreted as XML information (such as the bracket-based tags of HTML) the text area should be enclosed in a CDATA section to prevent the markup from interfering with XML validation of the CybOX document. If this attribute is absent, the implication is that no markup is being used.
    /// </summary>
    [XmlAttribute]
    public string structuring_format
    {
        get => _structuring_format;
        set => _structuring_format = value;
    }
    
    [XmlText]
    public string Value
    {
        get => _value;
        set => _value = value;
    }
}
}
#pragma warning restore
