// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class Structured_Text_TypeImagesImage
{
    #region Private fields
    private List<string> _image_Location;
    private List<string> _image_Title;
    #endregion
    
    /// <summary>
    /// Structured_Text_TypeImagesImage class constructor
    /// </summary>
    public Structured_Text_TypeImagesImage()
    {
        _image_Title = new List<string>();
        _image_Location = new List<string>();
    }
    
    [XmlElement("Image_Location")]
    public List<string> Image_Location
    {
        get => _image_Location;
        set => _image_Location = value;
    }
    
    [XmlElement("Image_Title")]
    public List<string> Image_Title
    {
        get => _image_Title;
        set => _image_Title = value;
    }
}
}
#pragma warning restore
