// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class Target_Attack_Surface_DescriptionTypeTarget_Functional_Service
{
    #region Private fields
    private List<Target_Attack_Surface_DescriptionTypeTarget_Functional_ServiceProtocol> _protocol;
    private string _id;
    private string _name;
    #endregion
    
    /// <summary>
    /// Target_Attack_Surface_DescriptionTypeTarget_Functional_Service class constructor
    /// </summary>
    public Target_Attack_Surface_DescriptionTypeTarget_Functional_Service()
    {
        _protocol = new List<Target_Attack_Surface_DescriptionTypeTarget_Functional_ServiceProtocol>();
    }
    
    [XmlElement("Protocol")]
    public List<Target_Attack_Surface_DescriptionTypeTarget_Functional_ServiceProtocol> Protocol
    {
        get => _protocol;
        set => _protocol = value;
    }
    
    [XmlAttribute(DataType="integer")]
    public string ID
    {
        get => _id;
        set => _id = value;
    }
    
    [XmlAttribute]
    public string Name
    {
        get => _name;
        set => _name = value;
    }
}
}
#pragma warning restore
