// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public enum Target_Attack_Surface_DescriptionTypeTargeted_OSI_Layer
{
    [XmlEnum("Physical Layer")]
    PhysicalLayer,
    [XmlEnum("Data Link Layer")]
    DataLinkLayer,
    [XmlEnum("Network Layer")]
    NetworkLayer,
    [XmlEnum("Transport Layer")]
    TransportLayer,
    [XmlEnum("Session Layer")]
    SessionLayer,
    [XmlEnum("Presentation Layer")]
    PresentationLayer,
    [XmlEnum("Application Layer")]
    ApplicationLayer,
}
}
#pragma warning restore
