// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://capec.mitre.org/capec-2")]
public partial class Target_Attack_Surface_DescriptionType
{
    #region Private fields
    private List<Target_Attack_Surface_DescriptionTypeTargeted_OSI_Layer> _targeted_OSI_Layers;
    private List<Target_Attack_Surface_DescriptionTypeTarget_Attack_Surface_Locality> _target_Attack_Surface_Localities;
    private List<Target_Attack_Surface_DescriptionTypeTarget_Attack_Surface_Type> _target_Attack_Surface_Types;
    private List<Target_Attack_Surface_DescriptionTypeTarget_Functional_Service> _target_Functional_Services;
    #endregion
    
    /// <summary>
    /// Target_Attack_Surface_DescriptionType class constructor
    /// </summary>
    public Target_Attack_Surface_DescriptionType()
    {
        _target_Functional_Services = new List<Target_Attack_Surface_DescriptionTypeTarget_Functional_Service>();
        _target_Attack_Surface_Types = new List<Target_Attack_Surface_DescriptionTypeTarget_Attack_Surface_Type>();
        _target_Attack_Surface_Localities = new List<Target_Attack_Surface_DescriptionTypeTarget_Attack_Surface_Locality>();
        _targeted_OSI_Layers = new List<Target_Attack_Surface_DescriptionTypeTargeted_OSI_Layer>();
    }
    
    [XmlArrayItem("Targeted_OSI_Layer", IsNullable=false)]
    public List<Target_Attack_Surface_DescriptionTypeTargeted_OSI_Layer> Targeted_OSI_Layers
    {
        get => _targeted_OSI_Layers;
        set => _targeted_OSI_Layers = value;
    }
    
    [XmlArrayItem("Target_Attack_Surface_Locality", IsNullable=false)]
    public List<Target_Attack_Surface_DescriptionTypeTarget_Attack_Surface_Locality> Target_Attack_Surface_Localities
    {
        get => _target_Attack_Surface_Localities;
        set => _target_Attack_Surface_Localities = value;
    }
    
    [XmlArrayItem("Target_Attack_Surface_Type", IsNullable=false)]
    public List<Target_Attack_Surface_DescriptionTypeTarget_Attack_Surface_Type> Target_Attack_Surface_Types
    {
        get => _target_Attack_Surface_Types;
        set => _target_Attack_Surface_Types = value;
    }
    
    [XmlArrayItem("Target_Functional_Service", IsNullable=false)]
    public List<Target_Attack_Surface_DescriptionTypeTarget_Functional_Service> Target_Functional_Services
    {
        get => _target_Functional_Services;
        set => _target_Functional_Services = value;
    }
}
}
#pragma warning restore
