// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The TimeType specifies various time properties for this construct.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class TimeType
{
    #region Private fields
    private DateTimeWithPrecisionType _start_Time;
    private DateTimeWithPrecisionType _end_Time;
    private DateTimeWithPrecisionType _produced_Time;
    private DateTimeWithPrecisionType _received_Time;
    #endregion
    
    /// <summary>
    /// TimeType class constructor
    /// </summary>
    public TimeType()
    {
        _received_Time = new DateTimeWithPrecisionType();
        _produced_Time = new DateTimeWithPrecisionType();
        _end_Time = new DateTimeWithPrecisionType();
        _start_Time = new DateTimeWithPrecisionType();
    }
    
    /// <summary>
    /// The Start_Time field is optional and describes the starting time for this construct. In order to avoid ambiguity, it is strongly suggest that all timestamps in this field include a specification of the timezone if it is known.
    /// </summary>
    public DateTimeWithPrecisionType Start_Time
    {
        get => _start_Time;
        set => _start_Time = value;
    }
    
    /// <summary>
    /// The End_Time field is optional and describes the ending time for this construct. In order to avoid ambiguity, it is strongly suggest that all timestamps in this field include a specification of the timezone if it is known.
    /// </summary>
    public DateTimeWithPrecisionType End_Time
    {
        get => _end_Time;
        set => _end_Time = value;
    }
    
    /// <summary>
    /// The Produced_Time field is optional and describes the time that this construct was produced. In order to avoid ambiguity, it is strongly suggest that all timestamps in this field include a specification of the timezone if it is known.
    /// </summary>
    public DateTimeWithPrecisionType Produced_Time
    {
        get => _produced_Time;
        set => _produced_Time = value;
    }
    
    /// <summary>
    /// The Received_Time field is optional and describes the time that this construct was received. In order to avoid ambiguity, it is strongly suggest that all timestamps in this field include a specification of the timezone if it is known.
    /// </summary>
    public DateTimeWithPrecisionType Received_Time
    {
        get => _received_Time;
        set => _received_Time = value;
    }
}
}
#pragma warning restore
