// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// Contains one reference to information or instances of a given tool.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public partial class ToolReferenceType
{
    #region Private fields
    private ToolReferenceTypeEnum _reference_type;
    private string _value;
    #endregion
    
    /// <summary>
    /// Indicates the nature of the referenced material (documentation, source, executable, etc.).
    /// </summary>
    [XmlAttribute]
    public ToolReferenceTypeEnum reference_type
    {
        get => _reference_type;
        set => _reference_type = value;
    }
    
    [XmlText(DataType="anyURI")]
    public string Value
    {
        get => _value;
        set => _value = value;
    }
}
}
#pragma warning restore
