// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    /// <summary>
/// The nature of referenced material regarding a tool.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(Namespace="http://cybox.mitre.org/common-2")]
public enum ToolReferenceTypeEnum
{
    /// <summary>
    /// The reference is to documentation about the identified tool.
    /// </summary>
    Documentation,
    /// <summary>
    /// The reference is to source code for the identified tool.
    /// </summary>
    Source,
    /// <summary>
    /// The reference is to where an executable version of the tool can be downloaded.
    /// </summary>
    Download,
    /// <summary>
    /// The reference is to the tool implemented as an online service.
    /// </summary>
    Execute,
    /// <summary>
    /// The reference is to material about the tool not covered by other values in this enumeration.
    /// </summary>
    Other,
}
}
#pragma warning restore
