// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Capec
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://capec.mitre.org/capec-2")]
public partial class ViewAudience
{
    #region Private fields
    private ViewAudienceStakeholder _stakeholder;
    private Structured_Text_Type _stakeholder_Description;
    #endregion
    
    /// <summary>
    /// ViewAudience class constructor
    /// </summary>
    public ViewAudience()
    {
        _stakeholder_Description = new Structured_Text_Type();
    }
    
    public ViewAudienceStakeholder Stakeholder
    {
        get => _stakeholder;
        set => _stakeholder = value;
    }
    
    public Structured_Text_Type Stakeholder_Description
    {
        get => _stakeholder_Description;
        set => _stakeholder_Description = value;
    }
}
}
#pragma warning restore
