// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.2.97.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ThreatsManager.Mitre.Cwe
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.Collections.Generic;

/// <summary>
/// The TaxonomyNameEnumeration simple type lists the different known taxomomies that can be mapped to CWE.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[XmlTypeAttribute(Namespace="http://cwe.mitre.org/cwe-6")]
public enum TaxonomyNameEnumeration
{
    [XmlEnumAttribute("7 Pernicious Kingdoms")]
    Item7PerniciousKingdoms,
    [XmlEnumAttribute("19 Deadly Sins")]
    Item19DeadlySins,
    Aslam,
    Bishop,
    CLASP,
    Landwehr,
    [XmlEnumAttribute("OMG ASCSM")]
    OMGASCSM,
    [XmlEnumAttribute("OMG ASCRM")]
    OMGASCRM,
    [XmlEnumAttribute("OMG ASCMM")]
    OMGASCMM,
    [XmlEnumAttribute("OMG ASCPEM")]
    OMGASCPEM,
    [XmlEnumAttribute("OWASP Top Ten 2004")]
    OWASPTopTen2004,
    [XmlEnumAttribute("OWASP Top Ten 2007")]
    OWASPTopTen2007,
    [XmlEnumAttribute("OWASP Top Ten")]
    OWASPTopTen,
    PLOVER,
    [XmlEnumAttribute("Protection Analysis")]
    ProtectionAnalysis,
    RISOS,
    [XmlEnumAttribute("Weber, Karger, Paradkar")]
    WeberKargerParadkar,
    WASC,
    [XmlEnumAttribute("CERT C Secure Coding")]
    CERTCSecureCoding,
    [XmlEnumAttribute("CERT C++ Secure Coding")]
    CERTCSecureCoding1,
    [XmlEnumAttribute("The CERT Oracle Secure Coding Standard for Java (2011)")]
    TheCERTOracleSecureCodingStandardforJava2011,
    [XmlEnumAttribute("SEI CERT C Coding Standard")]
    SEICERTCCodingStandard,
    [XmlEnumAttribute("SEI CERT C++ Coding Standard")]
    SEICERTCCodingStandard1,
    [XmlEnumAttribute("SEI CERT Oracle Coding Standard for Java")]
    SEICERTOracleCodingStandardforJava,
    [XmlEnumAttribute("SEI CERT Perl Coding Standard")]
    SEICERTPerlCodingStandard,
    [XmlEnumAttribute("Software Fault Patterns")]
    SoftwareFaultPatterns,
}
}
#pragma warning restore
