// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    /// <summary>
/// This element describes when this entry is primary
/// - where the weakness exists independent of other weaknesses, or
/// when this entry might be resultant - where the weakness is
/// typically related to the presence of some other weaknesses. The
/// Ordinality subelement identifies whether or not we are providing
/// context around when this entry is primary, or resultant. The
/// Ordinality_Description contains the description of the context
/// in which this entry is primary or resultant. It is important to
/// note that it is possible for the same entry to be primary in
/// some instances and resultant in others.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class CategoryWeakness_Ordinality
{
    #region Private fields
    private CategoryWeakness_OrdinalityOrdinality _ordinality;
    private Structured_Text_Type _ordinality_Description;
    #endregion
    
    /// <summary>
    /// CategoryWeakness_Ordinality class constructor
    /// </summary>
    public CategoryWeakness_Ordinality()
    {
        _ordinality_Description = new Structured_Text_Type();
    }
    
    /// <summary>
    /// This element indicates whether this
    /// weakness exists independent of other weaknesses,
    /// Primary, or whether it is the result of the presence
    /// of some other weaknesses,
    /// Resultant.
    /// </summary>
    public CategoryWeakness_OrdinalityOrdinality Ordinality
    {
        get
        {
            return _ordinality;
        }
        set
        {
            _ordinality = value;
        }
    }
    
    /// <summary>
    /// This element describes context in
    /// which this entry is either Primary or Resultant,
    /// depending on the corresponding value for
    /// Ordinality.
    /// </summary>
    public Structured_Text_Type Ordinality_Description
    {
        get
        {
            return _ordinality_Description;
        }
        set
        {
            _ordinality_Description = value;
        }
    }
}
}
#pragma warning restore
