// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    /// <summary>
/// This element identifies a single
/// class of operating systems, specified in
/// Operating_System_Class_Description, in which this
/// entry may exist. Suggested values include: Linux,
/// Windows, UNIX, BSD, and Mac OS.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class CategoryApplicable_PlatformsOperating_SystemsOperating_System_Class
{
    #region Private fields
    private string _operating_System_Class_Description;
    private Frequency_Type _prevalence;
    #endregion
    
    /// <summary>
    /// This subelement identifies
    /// families or groups of operating systems in which
    /// this weakness is likely to exist.
    /// </summary>
    [XmlAttribute]
    public string Operating_System_Class_Description
    {
        get
        {
            return _operating_System_Class_Description;
        }
        set
        {
            _operating_System_Class_Description = value;
        }
    }
    
    /// <summary>
    /// This attribute identifies the
    /// prevalence with which this weakness may occur
    /// within code that runs on the specified operating
    /// system within this operating system
    /// class.
    /// </summary>
    [XmlAttribute]
    public Frequency_Type Prevalence
    {
        get
        {
            return _prevalence;
        }
        set
        {
            _prevalence = value;
        }
    }
}
}
#pragma warning restore
