// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    /// <summary>
/// This structure describes mappings to nodes of
/// other taxonomies that are similar in meaning to this node.
/// Although this may sound similar to Source_Taxonomy,
/// Source_Taxonomy is designed to provide a history and pedigree
/// for the entry, whereas Taxonomy_Mapping allows similar nodes in
/// other collections to be identified as matching concepts with
/// this weakness. For example, Taxonomy_Mapping should be used to
/// map the CWE entries to their OWASP Top 10 equivalents. The sole
/// attribute is "Mapped_Taxonomy_Name" which is used to identify
/// the taxonomy to which this weakness is being mapped.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class CategoryTaxonomy_Mapping
{
    #region Private fields
    private string _mapped_Node_Name;
    private string _mapped_Node_ID;
    private CategoryTaxonomy_MappingMapping_Fit _mapping_Fit;
    private CategoryTaxonomy_MappingMapped_Taxonomy_Name _mapped_Taxonomy_Name;
    #endregion
    
    /// <summary>
    /// This element identifies the name of
    /// the entry to which this weakness is being mapped in
    /// taxonomy Taxonomy_Name.
    /// </summary>
    public string Mapped_Node_Name
    {
        get
        {
            return _mapped_Node_Name;
        }
        set
        {
            _mapped_Node_Name = value;
        }
    }
    
    /// <summary>
    /// This element identifies the ID of the
    /// entry to which this weakness is being mapped in
    /// taxonomy Taxonomy_Name.
    /// </summary>
    public string Mapped_Node_ID
    {
        get
        {
            return _mapped_Node_ID;
        }
        set
        {
            _mapped_Node_ID = value;
        }
    }
    
    /// <summary>
    /// This element identifies how close to
    /// the original taxonomy this node was mapped.
    /// </summary>
    public CategoryTaxonomy_MappingMapping_Fit Mapping_Fit
    {
        get
        {
            return _mapping_Fit;
        }
        set
        {
            _mapping_Fit = value;
        }
    }
    
    /// <summary>
    /// This attribute identifies the taxonomy to
    /// which this weakness has a similar or equivalent entry.
    /// </summary>
    [XmlAttribute]
    public CategoryTaxonomy_MappingMapped_Taxonomy_Name Mapped_Taxonomy_Name
    {
        get
        {
            return _mapped_Taxonomy_Name;
        }
        set
        {
            _mapped_Taxonomy_Name = value;
        }
    }
}
}
#pragma warning restore
