// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true)]
public enum CategoryTaxonomy_MappingMapped_Taxonomy_Name
{
    [XmlEnum("7 Pernicious Kingdoms")]
    Item7PerniciousKingdoms,
    [XmlEnum("19 Deadly Sins")]
    Item19DeadlySins,
    [XmlEnum("Anonymous Tool Vendor (under NDA)")]
    AnonymousToolVendorunderNDA,
    Aslam,
    Bishop,
    CLASP,
    Landwehr,
    [XmlEnum("OWASP Top Ten 2004")]
    OWASPTopTen2004,
    [XmlEnum("OWASP Top Ten 2007")]
    OWASPTopTen2007,
    PLOVER,
    [XmlEnum("Protection Analysis")]
    ProtectionAnalysis,
    RISOS,
    [XmlEnum("Weber, Karger, Paradkar")]
    WeberKargerParadkar,
    WASC,
    [XmlEnum("CERT C Secure Coding")]
    CERTCSecureCoding,
    [XmlEnum("CERT Java Secure Coding")]
    CERTJavaSecureCoding,
    [XmlEnum("CERT C++ Secure Coding")]
    CERTCSecureCoding1,
    [XmlEnum("Software Fault Patterns")]
    SoftwareFaultPatterns,
}
}
#pragma warning restore
