// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true)]
public enum CategoryDetection_MethodMethod_Effectiveness
{
    [XmlEnum("None/Rare")]
    NoneRare,
    Limited,
    Opportunistic,
    Moderate,
    High,
    [XmlEnum("SOAR High")]
    SOARHigh,
    [XmlEnum("SOAR Partial")]
    SOARPartial,
}
}
#pragma warning restore
