// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true)]
public enum CategoryApplicable_PlatformsTechnology_ClassTechnology_Name
{
    [XmlEnum("Web-Server")]
    WebServer,
    [XmlEnum("Web-Client")]
    WebClient,
    [XmlEnum("Database-Server")]
    DatabaseServer,
    [XmlEnum("Database-Client")]
    DatabaseClient,
}
}
#pragma warning restore
