// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true)]
public enum CategoryApplicable_PlatformsArchitectural_ParadigmArchitectural_Paradigm_Name
{
    Mainframe,
    [XmlEnum("Client-Server")]
    ClientServer,
    [XmlEnum("n-Tier")]
    nTier,
    [XmlEnum("Web-based")]
    Webbased,
    [XmlEnum("Mobile Application")]
    MobileApplication,
    SOA,
    [XmlEnum("Concurrent Systems Operating on Shared Resources")]
    ConcurrentSystemsOperatingonSharedResources,
}
}
#pragma warning restore
