// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    /// <summary>
/// This structure contains the Languages, Operating_Systems,
/// Hardware_Architectures, Architectural_Paradigms, Environments,
/// Technology_Classes or Common Platforms on which this entry may exist. This
/// should be filled out as much as possible for all Compound_Element and
/// Weakness entries.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class CategoryApplicable_Platforms
{
    #region Private fields
    private Languages_List_Type _languages;
    private CategoryApplicable_PlatformsOperating_Systems _operating_Systems;
    private CategoryApplicable_PlatformsHardware_Architectures _hardware_Architectures;
    private List<CategoryApplicable_PlatformsArchitectural_Paradigm> _architectural_Paradigms;
    private List<CategoryApplicable_PlatformsEnvironment> _environments;
    private List<CategoryApplicable_PlatformsTechnology_Class> _technology_Classes;
    private List<CategoryApplicable_PlatformsCommon_Platform_Reference> _common_Platform_References;
    private Structured_Text_Type _platform_Notes;
    #endregion
    
    /// <summary>
    /// CategoryApplicable_Platforms class constructor
    /// </summary>
    public CategoryApplicable_Platforms()
    {
        _platform_Notes = new Structured_Text_Type();
        _common_Platform_References = new List<CategoryApplicable_PlatformsCommon_Platform_Reference>();
        _technology_Classes = new List<CategoryApplicable_PlatformsTechnology_Class>();
        _environments = new List<CategoryApplicable_PlatformsEnvironment>();
        _architectural_Paradigms = new List<CategoryApplicable_PlatformsArchitectural_Paradigm>();
        _hardware_Architectures = new CategoryApplicable_PlatformsHardware_Architectures();
        _operating_Systems = new CategoryApplicable_PlatformsOperating_Systems();
        _languages = new Languages_List_Type();
    }
    
    /// <summary>
    /// This structure contains one or more Language
    /// elements which each represent a language in which this weakness
    /// may exist.
    /// </summary>
    public Languages_List_Type Languages
    {
        get
        {
            return _languages;
        }
        set
        {
            _languages = value;
        }
    }
    
    /// <summary>
    /// This element contains one or more
    /// Operating_System subelements which each represent an OS in which
    /// this weakness is likely to exist.
    /// </summary>
    public CategoryApplicable_PlatformsOperating_Systems Operating_Systems
    {
        get
        {
            return _operating_Systems;
        }
        set
        {
            _operating_Systems = value;
        }
    }
    
    /// <summary>
    /// This element contains one or more
    /// Hardware_Architecture subelements which each represent an
    /// architecture in which this weakness is likely to exist.
    /// </summary>
    public CategoryApplicable_PlatformsHardware_Architectures Hardware_Architectures
    {
        get
        {
            return _hardware_Architectures;
        }
        set
        {
            _hardware_Architectures = value;
        }
    }
    
    /// <summary>
    /// This element contains one or more
    /// Architectural_Paradigm subelements which each represent an
    /// architecture on which this weakness is likely to exist.
    /// </summary>
    [XmlArrayItem("Architectural_Paradigm", IsNullable=false)]
    public List<CategoryApplicable_PlatformsArchitectural_Paradigm> Architectural_Paradigms
    {
        get
        {
            return _architectural_Paradigms;
        }
        set
        {
            _architectural_Paradigms = value;
        }
    }
    
    /// <summary>
    /// This element contains one or more Environment
    /// subelements which each represent an environment in which this
    /// weakness may exist.
    /// </summary>
    [XmlArrayItem("Environment", IsNullable=false)]
    public List<CategoryApplicable_PlatformsEnvironment> Environments
    {
        get
        {
            return _environments;
        }
        set
        {
            _environments = value;
        }
    }
    
    /// <summary>
    /// This element contains one or more individual
    /// Technology_Class subelements which each represent a technology
    /// class in which this weakness is likely to exist.
    /// </summary>
    [XmlArrayItem("Technology_Class", IsNullable=false)]
    public List<CategoryApplicable_PlatformsTechnology_Class> Technology_Classes
    {
        get
        {
            return _technology_Classes;
        }
        set
        {
            _technology_Classes = value;
        }
    }
    
    /// <summary>
    /// The Common_Platforms element contains references
    /// to the Common Platform Enumeration, CPE, which will identify
    /// common platforms on which this weakness may occur. It has one or
    /// more Common_Platform elements as children and each child will
    /// point to a single CPE entry which is associated with this
    /// weakness.
    /// </summary>
    [XmlArrayItem("Common_Platform_Reference", IsNullable=false)]
    public List<CategoryApplicable_PlatformsCommon_Platform_Reference> Common_Platform_References
    {
        get
        {
            return _common_Platform_References;
        }
        set
        {
            _common_Platform_References = value;
        }
    }
    
    /// <summary>
    /// This element provides additional information
    /// related to the applicable platforms of a weakness if needed.
    /// </summary>
    public Structured_Text_Type Platform_Notes
    {
        get => _platform_Notes;
        set
        {
            _platform_Notes = value;
        }
    }
}
}
#pragma warning restore
