// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[XmlType(AnonymousType=true)]
public enum CategoryDetection_MethodMethod_Name
{
    [XmlEnum("Automated Analysis")]
    AutomatedAnalysis,
    [XmlEnum("Automated Dynamic Analysis")]
    AutomatedDynamicAnalysis,
    [XmlEnum("Automated Static Analysis")]
    AutomatedStaticAnalysis,
    Fuzzing,
    [XmlEnum("Manual Analysis")]
    ManualAnalysis,
    [XmlEnum("Manual Dynamic Analysis")]
    ManualDynamicAnalysis,
    [XmlEnum("Manual Static Analysis")]
    ManualStaticAnalysis,
    Other,
    [XmlEnum("White Box")]
    WhiteBox,
    [XmlEnum("Black Box")]
    BlackBox,
    [XmlEnum("Architecture / Design Review")]
    ArchitectureDesignReview,
    [XmlEnum("Automated Static Analysis - Source Code")]
    AutomatedStaticAnalysisSourceCode,
    [XmlEnum("Automated Static Analysis - Binary / Bytecode")]
    AutomatedStaticAnalysisBinaryBytecode,
    [XmlEnum("Dynamic Analysis with manual results interpretation")]
    DynamicAnalysiswithmanualresultsinterpretation,
    [XmlEnum("Dynamic Analysis with automated results interpretation")]
    DynamicAnalysiswithautomatedresultsinterpretation,
    [XmlEnum("Manual Static Analysis - Source Code")]
    ManualStaticAnalysisSourceCode,
    [XmlEnum("Manual Static Analysis - Binary / Bytecode")]
    ManualStaticAnalysisBinaryBytecode,
}
}
#pragma warning restore
