// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    /// <summary>
/// The Weakness_Catalog structure represents a collection of software
/// security issues (flaws, faults, bugs, vulnerabilities, weaknesses, etc). The name
/// used by CWE is usually "CWE". However, if this collection is a subset of CWE, then a
/// more appropriate name should be used. It has two required attributes: Catalog_Name
/// and Catalog_Version.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
[XmlRoot(Namespace="", IsNullable=false)]
public partial class Compound_Element
{
    #region Private fields
    private CategoryDescription _description;
    private List<Relationship> _relationships;
    private List<Structured_Text_Type> _relationship_Notes;
    private List<CategoryWeakness_Ordinality> _weakness_Ordinalities;
    private CategoryApplicable_Platforms _applicable_Platforms;
    private List<Structured_Text_Type> _maintenance_Notes;
    private List<Structured_Text_Type> _background_Details;
    private List<Structured_Text_Type> _other_Notes;
    private List<Alternate_TermsAlternate_Term> _alternate_Terms;
    private List<Structured_Text_Type> _terminology_Notes;
    private List<SDLC_Phase_Type> _time_of_Introduction;
    private List<Structured_Text_Type> _modes_of_Introduction;
    private List<Structured_Text_Type> _enabling_Factors_for_Exploitation;
    private CategoryLikelihood_of_Exploit _likelihood_of_Exploit;
    private List<Common_Consequence> _common_Consequences;
    private List<CategoryDetection_Method> _detection_Methods;
    private List<Mitigation> _potential_Mitigations;
    private CategoryCausal_Nature _causal_Nature;
    private List<CategoryDemonstrative_Example> _demonstrative_Examples;
    private List<CategoryObserved_Example> _observed_Examples;
    private List<Structured_Text_Type> _theoretical_Notes;
    private List<string> _functional_Areas;
    private List<CategoryRelevant_Property> _relevant_Properties;
    private List<CategoryAffected_Resource> _affected_Resources;
    private List<Structured_Text_Type> _research_Gaps;
    private List<Reference_Type> _references;
    private List<CategoryTaxonomy_Mapping> _taxonomy_Mappings;
    private List<Structured_Text_Type> _white_Box_Definitions;
    private List<Structured_Text_Type> _black_Box_Definitions;
    private List<CategoryRelated_Attack_Pattern> _related_Attack_Patterns;
    private Content_History _content_History;
    private string _id;
    private string _name;
    private Compound_ElementCompound_Element_Abstraction _compound_Element_Abstraction;
    private Compound_ElementCompound_Element_Structure _compound_Element_Structure;
    private Status_Type _status;
    #endregion
    
    /// <summary>
    /// Compound_Element class constructor
    /// </summary>
    public Compound_Element()
    {
        _content_History = new Content_History();
        _related_Attack_Patterns = new List<CategoryRelated_Attack_Pattern>();
        _black_Box_Definitions = new List<Structured_Text_Type>();
        _white_Box_Definitions = new List<Structured_Text_Type>();
        _taxonomy_Mappings = new List<CategoryTaxonomy_Mapping>();
        _references = new List<Reference_Type>();
        _research_Gaps = new List<Structured_Text_Type>();
        _affected_Resources = new List<CategoryAffected_Resource>();
        _relevant_Properties = new List<CategoryRelevant_Property>();
        _functional_Areas = new List<string>();
        _theoretical_Notes = new List<Structured_Text_Type>();
        _observed_Examples = new List<CategoryObserved_Example>();
        _demonstrative_Examples = new List<CategoryDemonstrative_Example>();
        _potential_Mitigations = new List<Mitigation>();
        _detection_Methods = new List<CategoryDetection_Method>();
        _common_Consequences = new List<Common_Consequence>();
        _enabling_Factors_for_Exploitation = new List<Structured_Text_Type>();
        _modes_of_Introduction = new List<Structured_Text_Type>();
        _time_of_Introduction = new List<SDLC_Phase_Type>();
        _terminology_Notes = new List<Structured_Text_Type>();
        _alternate_Terms = new List<Alternate_TermsAlternate_Term>();
        _other_Notes = new List<Structured_Text_Type>();
        _background_Details = new List<Structured_Text_Type>();
        _maintenance_Notes = new List<Structured_Text_Type>();
        _applicable_Platforms = new CategoryApplicable_Platforms();
        _weakness_Ordinalities = new List<CategoryWeakness_Ordinality>();
        _relationship_Notes = new List<Structured_Text_Type>();
        _relationships = new List<Relationship>();
        _description = new CategoryDescription();
    }
    
    public CategoryDescription Description
    {
        get
        {
            return _description;
        }
        set
        {
            _description = value;
        }
    }
    
    [XmlArrayItem("Relationship", IsNullable=false)]
    public List<Relationship> Relationships
    {
        get
        {
            return _relationships;
        }
        set
        {
            _relationships = value;
        }
    }
    
    [XmlArrayItem("Relationship_Note", IsNullable=false)]
    public List<Structured_Text_Type> Relationship_Notes
    {
        get
        {
            return _relationship_Notes;
        }
        set
        {
            _relationship_Notes = value;
        }
    }
    
    [XmlArrayItem("Weakness_Ordinality", IsNullable=false)]
    public List<CategoryWeakness_Ordinality> Weakness_Ordinalities
    {
        get
        {
            return _weakness_Ordinalities;
        }
        set
        {
            _weakness_Ordinalities = value;
        }
    }
    
    public CategoryApplicable_Platforms Applicable_Platforms
    {
        get
        {
            return _applicable_Platforms;
        }
        set
        {
            _applicable_Platforms = value;
        }
    }
    
    [XmlArrayItem("Maintenance_Note", IsNullable=false)]
    public List<Structured_Text_Type> Maintenance_Notes
    {
        get
        {
            return _maintenance_Notes;
        }
        set
        {
            _maintenance_Notes = value;
        }
    }
    
    [XmlArrayItem("Background_Detail", IsNullable=false)]
    public List<Structured_Text_Type> Background_Details
    {
        get
        {
            return _background_Details;
        }
        set
        {
            _background_Details = value;
        }
    }
    
    [XmlArrayItem("Note", IsNullable=false)]
    public List<Structured_Text_Type> Other_Notes
    {
        get
        {
            return _other_Notes;
        }
        set
        {
            _other_Notes = value;
        }
    }
    
    [XmlArrayItem("Alternate_Term", IsNullable=false)]
    public List<Alternate_TermsAlternate_Term> Alternate_Terms
    {
        get
        {
            return _alternate_Terms;
        }
        set
        {
            _alternate_Terms = value;
        }
    }
    
    [XmlArrayItem("Terminology_Note", IsNullable=false)]
    public List<Structured_Text_Type> Terminology_Notes
    {
        get
        {
            return _terminology_Notes;
        }
        set
        {
            _terminology_Notes = value;
        }
    }
    
    [XmlArrayItem("Introductory_Phase", IsNullable=false)]
    public List<SDLC_Phase_Type> Time_of_Introduction
    {
        get
        {
            return _time_of_Introduction;
        }
        set
        {
            _time_of_Introduction = value;
        }
    }
    
    [XmlArrayItem("Mode_of_Introduction", IsNullable=false)]
    public List<Structured_Text_Type> Modes_of_Introduction
    {
        get
        {
            return _modes_of_Introduction;
        }
        set
        {
            _modes_of_Introduction = value;
        }
    }
    
    [XmlArrayItem("Enabling_Factor_for_Exploitation", IsNullable=false)]
    public List<Structured_Text_Type> Enabling_Factors_for_Exploitation
    {
        get
        {
            return _enabling_Factors_for_Exploitation;
        }
        set
        {
            _enabling_Factors_for_Exploitation = value;
        }
    }
    
    public CategoryLikelihood_of_Exploit Likelihood_of_Exploit
    {
        get
        {
            return _likelihood_of_Exploit;
        }
        set
        {
            _likelihood_of_Exploit = value;
        }
    }
    
    [XmlArrayItem("Common_Consequence", IsNullable=false)]
    public List<Common_Consequence> Common_Consequences
    {
        get
        {
            return _common_Consequences;
        }
        set
        {
            _common_Consequences = value;
        }
    }
    
    [XmlArrayItem("Detection_Method", IsNullable=false)]
    public List<CategoryDetection_Method> Detection_Methods
    {
        get
        {
            return _detection_Methods;
        }
        set
        {
            _detection_Methods = value;
        }
    }
    
    [XmlArrayItem("Mitigation", IsNullable=false)]
    public List<Mitigation> Potential_Mitigations
    {
        get
        {
            return _potential_Mitigations;
        }
        set
        {
            _potential_Mitigations = value;
        }
    }
    
    public CategoryCausal_Nature Causal_Nature
    {
        get
        {
            return _causal_Nature;
        }
        set
        {
            _causal_Nature = value;
        }
    }
    
    [XmlArrayItem("Demonstrative_Example", IsNullable=false)]
    public List<CategoryDemonstrative_Example> Demonstrative_Examples
    {
        get
        {
            return _demonstrative_Examples;
        }
        set
        {
            _demonstrative_Examples = value;
        }
    }
    
    [XmlArrayItem("Observed_Example", IsNullable=false)]
    public List<CategoryObserved_Example> Observed_Examples
    {
        get
        {
            return _observed_Examples;
        }
        set
        {
            _observed_Examples = value;
        }
    }
    
    [XmlArrayItem("Theoretical_Note", IsNullable=false)]
    public List<Structured_Text_Type> Theoretical_Notes
    {
        get
        {
            return _theoretical_Notes;
        }
        set
        {
            _theoretical_Notes = value;
        }
    }
    
    [XmlArrayItem("Functional_Area", IsNullable=false)]
    public List<string> Functional_Areas
    {
        get
        {
            return _functional_Areas;
        }
        set
        {
            _functional_Areas = value;
        }
    }
    
    [XmlArrayItem("Relevant_Property", IsNullable=false)]
    public List<CategoryRelevant_Property> Relevant_Properties
    {
        get
        {
            return _relevant_Properties;
        }
        set
        {
            _relevant_Properties = value;
        }
    }
    
    [XmlArrayItem("Affected_Resource", IsNullable=false)]
    public List<CategoryAffected_Resource> Affected_Resources
    {
        get
        {
            return _affected_Resources;
        }
        set
        {
            _affected_Resources = value;
        }
    }
    
    [XmlArrayItem("Research_Gap", IsNullable=false)]
    public List<Structured_Text_Type> Research_Gaps
    {
        get
        {
            return _research_Gaps;
        }
        set
        {
            _research_Gaps = value;
        }
    }
    
    [XmlArrayItem("Reference", IsNullable=false)]
    public List<Reference_Type> References
    {
        get
        {
            return _references;
        }
        set
        {
            _references = value;
        }
    }
    
    [XmlArrayItem("Taxonomy_Mapping", IsNullable=false)]
    public List<CategoryTaxonomy_Mapping> Taxonomy_Mappings
    {
        get
        {
            return _taxonomy_Mappings;
        }
        set
        {
            _taxonomy_Mappings = value;
        }
    }
    
    [XmlArrayItem("White_Box_Definition", IsNullable=false)]
    public List<Structured_Text_Type> White_Box_Definitions
    {
        get
        {
            return _white_Box_Definitions;
        }
        set
        {
            _white_Box_Definitions = value;
        }
    }
    
    [XmlArrayItem("Black_Box_Definition", IsNullable=false)]
    public List<Structured_Text_Type> Black_Box_Definitions
    {
        get
        {
            return _black_Box_Definitions;
        }
        set
        {
            _black_Box_Definitions = value;
        }
    }
    
    [XmlArrayItem("Related_Attack_Pattern", IsNullable=false)]
    public List<CategoryRelated_Attack_Pattern> Related_Attack_Patterns
    {
        get
        {
            return _related_Attack_Patterns;
        }
        set
        {
            _related_Attack_Patterns = value;
        }
    }
    
    public Content_History Content_History
    {
        get
        {
            return _content_History;
        }
        set
        {
            _content_History = value;
        }
    }
    
    [XmlAttribute(DataType="integer")]
    public string ID
    {
        get
        {
            return _id;
        }
        set
        {
            _id = value;
        }
    }
    
    [XmlAttribute]
    public string Name
    {
        get
        {
            return _name;
        }
        set
        {
            _name = value;
        }
    }
    
    [XmlAttribute]
    public Compound_ElementCompound_Element_Abstraction Compound_Element_Abstraction
    {
        get
        {
            return _compound_Element_Abstraction;
        }
        set
        {
            _compound_Element_Abstraction = value;
        }
    }
    
    [XmlAttribute]
    public Compound_ElementCompound_Element_Structure Compound_Element_Structure
    {
        get
        {
            return _compound_Element_Structure;
        }
        set
        {
            _compound_Element_Structure = value;
        }
    }
    
    [XmlAttribute]
    public Status_Type Status
    {
        get
        {
            return _status;
        }
        set
        {
            _status = value;
        }
    }
}
}
#pragma warning restore
