// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
[XmlRoot(Namespace="", IsNullable=false)]
public partial class Content_History
{
    #region Private fields
    private List<Content_HistorySubmission> _submission;
    private List<Content_HistoryContribution> _contribution;
    private List<Content_HistoryModification> _modification;
    private List<Content_HistoryPrevious_Entry_Name> _previous_Entry_Names;
    #endregion
    
    /// <summary>
    /// Content_History class constructor
    /// </summary>
    public Content_History()
    {
        _previous_Entry_Names = new List<Content_HistoryPrevious_Entry_Name>();
        _modification = new List<Content_HistoryModification>();
        _contribution = new List<Content_HistoryContribution>();
        _submission = new List<Content_HistorySubmission>();
    }
    
    [XmlElement("Submission")]
    public List<Content_HistorySubmission> Submission
    {
        get
        {
            return _submission;
        }
        set
        {
            _submission = value;
        }
    }
    
    [XmlElement("Contribution")]
    public List<Content_HistoryContribution> Contribution
    {
        get
        {
            return _contribution;
        }
        set
        {
            _contribution = value;
        }
    }
    
    [XmlElement("Modification")]
    public List<Content_HistoryModification> Modification
    {
        get
        {
            return _modification;
        }
        set
        {
            _modification = value;
        }
    }
    
    [XmlArrayItem("Previous_Entry_Name", IsNullable=false)]
    public List<Content_HistoryPrevious_Entry_Name> Previous_Entry_Names
    {
        get
        {
            return _previous_Entry_Names;
        }
        set
        {
            _previous_Entry_Names = value;
        }
    }
}
}
#pragma warning restore
