// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
public enum Language_Type
{
    C,
    [XmlEnum("C++")]
    C1,
    [XmlEnum("C#")]
    C2,
    Java,
    JSP,
    Javascript,
    [XmlEnum("ASP.NET")]
    ASPNET,
    SQL,
    Python,
    Perl,
    PHP,
    SOAP,
    Ruby,
    Shell,
    PseudoCode,
    [XmlEnum(".NET")]
    NET,
    Assembly,
    XML,
    HTML,
    [XmlEnum("Objective-C")]
    ObjectiveC,
}
}
#pragma warning restore
