// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
[DebuggerStepThrough]
[DesignerCategory("code")]
[XmlType(AnonymousType=true)]
public partial class RelationshipRelationship_View_ID
{
    #region Private fields
    private RelationshipRelationship_View_IDOrdinal _ordinal;
    private string _value;
    #endregion
    
    [XmlAttribute]
    public RelationshipRelationship_View_IDOrdinal Ordinal
    {
        get
        {
            return _ordinal;
        }
        set
        {
            _ordinal = value;
        }
    }
    
    [XmlText(DataType="integer")]
    public string Value
    {
        get
        {
            return _value;
        }
        set
        {
            _value = value;
        }
    }
}
}
#pragma warning restore
