// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.44
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace ThreatsManager.Extensions.Panels.ThreatSources.Cwe
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
[Serializable]
public enum SDLC_Phase_Type
{
    Policy,
    Requirements,
    [XmlEnum("Architecture and Design")]
    ArchitectureandDesign,
    Implementation,
    Testing,
    Bundling,
    Distribution,
    Installation,
    Patch,
    Documentation,
    Porting,
    [XmlEnum("System Configuration")]
    SystemConfiguration,
    Operation,
    [XmlEnum("Build and Compilation")]
    BuildandCompilation,
}
}
#pragma warning restore
