// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.94.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ThreatsManager.Mitre
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using Newtonsoft.Json;
using System.IO;
using System.Text;
using System.Collections.Generic;

[DebuggerStepThrough]
[Newtonsoft.Json.JsonObjectAttribute("rootSchemaObjectsBody_multipart", MemberSerialization=MemberSerialization.OptIn)]
public partial class rootSchemaObjectsBody_multipart
{
    #region Private fields
    private List<object> _items;
    private string _body;
    private string _body_raw_ref;
    private string _content_type;
    private string _content_disposition;
    #endregion
    
    public rootSchemaObjectsBody_multipart()
    {
        _items = new List<object>();
    }
    
    [Newtonsoft.Json.JsonPropertyAttribute()]
    public List<object> Items
    {
        get
        {
            return _items;
        }
        set
        {
            _items = value;
        }
    }
    
    [Newtonsoft.Json.JsonPropertyAttribute()]
    public string body
    {
        get
        {
            return _body;
        }
        set
        {
            _body = value;
        }
    }
    
    [Newtonsoft.Json.JsonPropertyAttribute()]
    public string body_raw_ref
    {
        get
        {
            return _body_raw_ref;
        }
        set
        {
            _body_raw_ref = value;
        }
    }
    
    [Newtonsoft.Json.JsonPropertyAttribute()]
    public string content_type
    {
        get
        {
            return _content_type;
        }
        set
        {
            _content_type = value;
        }
    }
    
    [Newtonsoft.Json.JsonPropertyAttribute()]
    public string content_disposition
    {
        get
        {
            return _content_disposition;
        }
        set
        {
            _content_disposition = value;
        }
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current rootSchemaObjectsBody_multipart object into an json string
    /// </summary>
    public virtual string Serialize()
    {
        Newtonsoft.Json.JsonSerializerSettings settings = new Newtonsoft.Json.JsonSerializerSettings();
        return JsonConvert.SerializeObject(this, settings);
    }
    
    /// <summary>
    /// Deserializes rootSchemaObjectsBody_multipart object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output rootSchemaObjectsBody_multipart object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out rootSchemaObjectsBody_multipart obj, out Exception exception)
    {
        exception = null;
        obj = default(rootSchemaObjectsBody_multipart);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out rootSchemaObjectsBody_multipart obj)
    {
        Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public static rootSchemaObjectsBody_multipart Deserialize(string input)
    {
        Newtonsoft.Json.JsonSerializerSettings settings = new Newtonsoft.Json.JsonSerializerSettings();
        return JsonConvert.DeserializeObject<rootSchemaObjectsBody_multipart>(input, settings);
    }
    #endregion
    
    public virtual void SaveToFile(string fileName)
    {
        StreamWriter streamWriter = null;
        try
        {
            string dataString = Serialize();
            FileInfo outputFile = new FileInfo(fileName);
            streamWriter = outputFile.CreateText();
            streamWriter.WriteLine(dataString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    public static rootSchemaObjectsBody_multipart LoadFromFile(string fileName)
    {
        FileStream file = null;
        StreamReader sr = null;
        try
        {
            file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new StreamReader(file);
            string dataString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(dataString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
}
}
#pragma warning restore
