// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.98.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ThreatsManager.Mitre.Stix
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.IO;
using System.Text;
using System.Collections.Generic;

[DebuggerStepThrough]
[Newtonsoft.Json.JsonObjectAttribute("RootSchemabundleObjectsGranular_markings", MemberSerialization=MemberSerialization.OptIn)]
public partial class RootSchemabundleObjectsGranular_markings
{
    #region Private fields
    private List<string> _selectors;
    private string _lang;
    private object _marking_ref;
    #endregion
    
    public RootSchemabundleObjectsGranular_markings()
    {
        _selectors = new List<string>();
    }
    
    [Newtonsoft.Json.JsonPropertyAttribute()]
    public List<string> selectors
    {
        get
        {
            return _selectors;
        }
        set
        {
            _selectors = value;
        }
    }
    
    [Newtonsoft.Json.JsonPropertyAttribute()]
    public string lang
    {
        get
        {
            return _lang;
        }
        set
        {
            _lang = value;
        }
    }
    
    [Newtonsoft.Json.JsonPropertyAttribute()]
    public object marking_ref
    {
        get
        {
            return _marking_ref;
        }
        set
        {
            _marking_ref = value;
        }
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current RootSchemabundleObjectsGranular_markings object into an json string
    /// </summary>
    public virtual string Serialize()
    {
        Newtonsoft.Json.JsonSerializerSettings settings = new Newtonsoft.Json.JsonSerializerSettings();
        return JsonConvert.SerializeObject(this, settings);
    }
    
    /// <summary>
    /// Deserializes RootSchemabundleObjectsGranular_markings object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output RootSchemabundleObjectsGranular_markings object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out RootSchemabundleObjectsGranular_markings obj, out Exception exception)
    {
        exception = null;
        obj = default(RootSchemabundleObjectsGranular_markings);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out RootSchemabundleObjectsGranular_markings obj)
    {
        Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public static RootSchemabundleObjectsGranular_markings Deserialize(string input)
    {
        Newtonsoft.Json.JsonSerializerSettings settings = new Newtonsoft.Json.JsonSerializerSettings();
        return JsonConvert.DeserializeObject<RootSchemabundleObjectsGranular_markings>(input, settings);
    }
    #endregion
    
    public virtual void SaveToFile(string fileName)
    {
        StreamWriter streamWriter = null;
        try
        {
            string dataString = Serialize();
            FileInfo outputFile = new FileInfo(fileName);
            streamWriter = outputFile.CreateText();
            streamWriter.WriteLine(dataString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    public static RootSchemabundleObjectsGranular_markings LoadFromFile(string fileName)
    {
        FileStream file = null;
        StreamReader sr = null;
        try
        {
            file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new StreamReader(file);
            string dataString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(dataString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
}
}
#pragma warning restore
