// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.94.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ThreatsManager.Mitre
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using Newtonsoft.Json;
using System.IO;
using System.Text;
using System.Collections.Generic;

public enum rootSchemaObjectsSpec_version
{
    [XmlEnumAttribute("2.0")]
    [EnumMember(Value="2.0")]
    Item20,
    [XmlEnumAttribute("2.1")]
    [EnumMember(Value="2.1")]
    Item21,
}
}
#pragma warning restore
